language: r
sudo: false
cache: packages

matrix:
  include:
   - r: 3.2
   - r: 3.3
   - r: 3.4
   - r: 3.5
   - r: release
   - r: devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

env:
  global:
    - NOT_CRAN=yes
